spring:
  data:
    mongodb:
      database: ${MONGO_DB}
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@ds047197.mlab.com:47197/heroku_1lp8qhqq?retryWrites=false

google:
  client-id: ${GOOGLE_CLIENT_ID}
  client-secret: ${GOOGLE_CLIENT_SECRET}