registration:
  mail:
    owner-address: roadmountain.shop@gmail.com
    provider-address: sranliu1993@gmail.com

    csv-title: "[TEST]Activation list from cloud"
    activate-title: "[TEST]【SIMカード開通】登録完了のご案内"